# Generated by Django 4.2.5 on 2023-09-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSiteApp', '0002_taskcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='task_content',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
