# Generated by Django 4.2.5 on 2023-09-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSiteApp', '0003_mytasks_open_alter_mytasks_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
    ]
