# Generated by Django 4.2.5 on 2023-09-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSiteApp', '0004_mytasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
