# Generated by Django 4.2.5 on 2023-09-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSiteApp', '0010_conversation_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTasks',
        ),
        migrations.DeleteModel(
            name='TaskComments',
        ),
    ]
