# Generated by Django 4.2.7 on 2023-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSiteApp', '0011_delete_mytasks_delete_taskcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskslistrows',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
